

import java.io.File;
import java.io.FileWriter;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class DarazFrame extends javax.swing.JFrame {

    static DarazFrame hpage;
         int result;
    /**
     * Creates new form DarazFrame
     */
    public DarazFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        TotalTakaTextField = new javax.swing.JTextField();
        ResetButton3 = new javax.swing.JButton();
        InfojButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ProductsName = new javax.swing.JComboBox<>();
        ProdQuantityTextField = new javax.swing.JTextField();
        ProdPriceTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel5.setText("Daraz Store");

        jButton2.setText("Total Price");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        TotalTakaTextField.setEditable(false);
        TotalTakaTextField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        ResetButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ResetButton3.setText("Reset");
        ResetButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButton3ActionPerformed(evt);
            }
        });

        InfojButton3.setBackground(new java.awt.Color(0, 102, 204));
        InfojButton3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        InfojButton3.setText("Daraz Panel");
        InfojButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfojButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Product Price");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Product quantity");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Products List");

        ProductsName.setBackground(new java.awt.Color(0, 102, 102));
        ProductsName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ProductsName.setMaximumRowCount(18);
        ProductsName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "R15 V3 (Bike)", "Asus Vivo Book (Laptop)", "SSD_512 GB ", "LCD Monitor_19 inch", "HDD_1 TB", "Sumsang TV", "Men's Fashon Gift Card", "Brazil Jersy", "Football", "Electronic Bike", "Mi Note 10 Smartphone", "RGB Keyboard", "CocaCola_400ml", "Meat" }));
        ProductsName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductsNameActionPerformed(evt);
            }
        });

        ProdQuantityTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ProdQuantityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdQuantityTextFieldActionPerformed(evt);
            }
        });

        ProdPriceTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ProdPriceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdPriceTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setText(" X");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Show Price");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton3.setText("Place Order");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton4.setText("Store Information");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(ProductsName, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addComponent(ProdQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4)
                                        .addGap(30, 30, 30)
                                        .addComponent(ProdPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(265, 265, 265)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(InfojButton3)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(37, 37, 37)
                                    .addComponent(TotalTakaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(ResetButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addComponent(jLabel5)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductsName, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProdQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProdPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalTakaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(ResetButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(InfojButton3))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ProdPriceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdPriceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProdPriceTextFieldActionPerformed

    private void ProdQuantityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdQuantityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProdQuantityTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      String a = ProductsName.getItemAt(ProductsName.getSelectedIndex());
      if(a.equals("R15 V3 (Bike)")){
     JOptionPane.showMessageDialog(this, "This product Price is 520000 Taka");
      } 
       else if(a.equals("Asus Vivo Book (Laptop)")){
     JOptionPane.showMessageDialog(this, "This product Price is 75000 Taka");}
      else if(a.equals("SSD_512 GB")){
     JOptionPane.showMessageDialog(this, "This product Price is 4000 Taka");}
       else if(a.equals("LCD Monitor_19 inch")){
     JOptionPane.showMessageDialog(this, "This product Price is 20000 Taka");}
       else if(a.equals("HDD_1 TB")){
     JOptionPane.showMessageDialog(this, "This product Price is 7000 Taka");}
       else if(a.equals("Sumsang TV")){
     JOptionPane.showMessageDialog(this, "This product Price is 40000 Taka");}
       else if(a.equals("Men's Fashon Gift Card")){
     JOptionPane.showMessageDialog(this, "This product Price is 2000 Taka");}
       else if(a.equals("Brazil Jersy")){
     JOptionPane.showMessageDialog(this, "This product Price is 1100 Taka");} 
      else if(a.equals("Football")){
     JOptionPane.showMessageDialog(this, "This product Price is 500 Taka");}
      else if(a.equals("Electronic Bike")){
     JOptionPane.showMessageDialog(this, "This product Price is 30000 Taka");}
       else if(a.equals("Mi Note 10 Smartphone")){
     JOptionPane.showMessageDialog(this, "This product Price is 30000 Taka");}
       else if(a.equals("RGB Keyboard")){
     JOptionPane.showMessageDialog(this, "This product Price is 3500 Taka");}
       else if(a.equals("CocaCola_400ml")){
     JOptionPane.showMessageDialog(this, "This product Price is 30 Taka");}
       else if(a.equals("Simvastatin")){
     JOptionPane.showMessageDialog(this, "This product Price is 500 Taka");}
      
      // TODO add your handling code here: 
//      R15 V3 (Bike)
//      Asus Vivo Book (Laptop)
//      SSD_512 GB 
//      LCD Monitor_19 inch
//      HDD_1 TB
//      Sumsang TV
//      Men's Fashon Gift Card
//      Brazil Jersy
//      Football
//      Electronic Bike
//      Mi Note 10 Smartphone
//      RGB Keyboard
//      CocaCola_400ml
//      Meat_1 kg
      //
    }//GEN-LAST:event_jButton1ActionPerformed
       
    
    
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    int MQ1=0;
     try{   
     MQ1 =Integer.parseInt(ProdQuantityTextField.getText());
     }catch(NumberFormatException e){
     JOptionPane.showMessageDialog(this,"Wrong Input");
     }
      int MP2=Integer.parseInt(ProdPriceTextField.getText());    
      TotalPrice c1=new TotalPrice(MQ1,MP2);
      result=c1.price();
      saveprice();
     TotalTakaTextField.setText(String.valueOf(result));        
        


// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    void saveprice(){
    try{
          File f = new File("TotalSell.txt");
          FileWriter fw = new FileWriter(f,true);
          fw.write(String.valueOf(result));
          fw.write("\r\n");
          fw.close();
      }
      catch (Exception e)
      {
           JOptionPane.showMessageDialog(this,"File not found");
      }
    
    }
    
    private void ResetButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButton3ActionPerformed
         ProdQuantityTextField.setText(null);
         ProdPriceTextField.setText(null); 
         TotalTakaTextField.setText(null);        // TODO add your handling code here:
    }//GEN-LAST:event_ResetButton3ActionPerformed

    private void InfojButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfojButton3ActionPerformed
         InfoFrame f2=new InfoFrame();
         f2.setVisible(true);
         dispose();             
    }//GEN-LAST:event_InfojButton3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      CartFrame f3=new CartFrame();
      f3.setVisible(true);
         dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ProductsNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductsNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductsNameActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     AddressFrame f4=new AddressFrame();
      f4.setVisible(true);
         dispose();        
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DarazFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DarazFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DarazFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DarazFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DarazFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InfojButton3;
    private javax.swing.JTextField ProdPriceTextField;
    private javax.swing.JTextField ProdQuantityTextField;
    private javax.swing.JComboBox<String> ProductsName;
    private javax.swing.JButton ResetButton3;
    private javax.swing.JTextField TotalTakaTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
