
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class InfoFrame extends javax.swing.JFrame {

    /**
     * Creates new form InfoFrame
     */
    public InfoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JhonButton1 = new javax.swing.JButton();
        SmithButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        RokyButton3 = new javax.swing.JButton();
        SiamButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        IDTextField1 = new javax.swing.JTextField();
        NameTextField2 = new javax.swing.JTextField();
        PostTextField3 = new javax.swing.JTextField();
        BackButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        JhonButton1.setBackground(new java.awt.Color(255, 102, 102));
        JhonButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JhonButton1.setText("Jhon");
        JhonButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JhonButton1ActionPerformed(evt);
            }
        });

        SmithButton2.setBackground(new java.awt.Color(255, 102, 102));
        SmithButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SmithButton2.setText("Smith");
        SmithButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SmithButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 0, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Clear All");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        RokyButton3.setBackground(new java.awt.Color(255, 102, 102));
        RokyButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RokyButton3.setText("Roky");
        RokyButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RokyButton3ActionPerformed(evt);
            }
        });

        SiamButton4.setBackground(new java.awt.Color(255, 102, 102));
        SiamButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SiamButton4.setText("Siam");
        SiamButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiamButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 28)); // NOI18N
        jLabel1.setText("Daraz Employee Information");

        IDTextField1.setEditable(false);
        IDTextField1.setBackground(new java.awt.Color(0, 102, 102));
        IDTextField1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        IDTextField1.setText("ID");

        NameTextField2.setEditable(false);
        NameTextField2.setBackground(new java.awt.Color(0, 102, 102));
        NameTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NameTextField2.setText("Name");
        NameTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextField2ActionPerformed(evt);
            }
        });

        PostTextField3.setEditable(false);
        PostTextField3.setBackground(new java.awt.Color(0, 102, 102));
        PostTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PostTextField3.setText("Post");

        BackButton5.setBackground(new java.awt.Color(204, 0, 0));
        BackButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BackButton5.setText("Back");
        BackButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButton5MouseClicked(evt);
            }
        });
        BackButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BackButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SmithButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RokyButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JhonButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SiamButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PostTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(jLabel1)
                .addContainerGap(319, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(JhonButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SmithButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(RokyButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SiamButton4)
                        .addGap(138, 138, 138)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BackButton5)
                            .addComponent(jButton1))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(IDTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NameTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PostTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JhonButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JhonButton1ActionPerformed
        Employee Jhon= new Employee("155555","Jhon","Manager");
        
        NameTextField2.setText(Jhon.id);
        IDTextField1.setText(Jhon.name);
        PostTextField3.setText(Jhon.post);
    }//GEN-LAST:event_JhonButton1ActionPerformed

    private void SmithButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SmithButton2ActionPerformed
      Employee Smith= new Employee("166665","Smith","Product Manager");
        
        NameTextField2.setText(Smith.id);
        IDTextField1.setText(Smith.name);
        PostTextField3.setText(Smith.post);
    }//GEN-LAST:event_SmithButton2ActionPerformed

    private void RokyButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RokyButton3ActionPerformed
        Employee Roky= new Employee("177775","Roky","Delivery Man");
        
        NameTextField2.setText(Roky.id);
        IDTextField1.setText(Roky.name);
        PostTextField3.setText(Roky.post);// TODO add your handling code here:
    }//GEN-LAST:event_RokyButton3ActionPerformed

    private void SiamButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiamButton4ActionPerformed
       Employee Siam= new Employee("188885","Siam","Devlivery Man");
        
        NameTextField2.setText(Siam.id);
        IDTextField1.setText(Siam.name);
        PostTextField3.setText(Siam.post);  
    }//GEN-LAST:event_SiamButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     NameTextField2.setText(null);
     IDTextField1.setText(null);
     PostTextField3.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

                                            

    private void BackButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButton5ActionPerformed
        DarazFrame f1= new DarazFrame();
        f1.setVisible(true);
        dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_BackButton5ActionPerformed

    private void BackButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButton5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BackButton5MouseClicked

    private void NameTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton5;
    private javax.swing.JTextField IDTextField1;
    private javax.swing.JButton JhonButton1;
    private javax.swing.JTextField NameTextField2;
    private javax.swing.JTextField PostTextField3;
    private javax.swing.JButton RokyButton3;
    private javax.swing.JButton SiamButton4;
    private javax.swing.JButton SmithButton2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
